version: '3'
services:
  install-tomcat:
    image: 'tomcat:9.0.78'
    ports:
    - '8081-8085:8080'
    volumes:
    - '/root/.jenkins/workspace/docker-compose-deploy/gameoflife-web/target/gameoflife.war:/usr/local/tomcat/webapps'
