---
- name: Deploy war on Tomcat
  hosts: devlinux
  become: true

  tasks:

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.zip"  # Change to the desired Tomcat version
        dest: /apache-tomcat-9.0.76.zip

    - name: Extract Tomcat
      unarchive:
        src: /apache-tomcat-9.0.76.zip
        dest: /
        remote_src: yes
        creates: /apache-tomcat-9.0.76  # Adjust to the Tomcat version you're downloading

    - name: Start Tomcat
      command: "apache-tomcat-9.0.76/bin/startup.sh"

    - name: Set permissions on the directory
      file:
        path: /apache-tomcat-9.0.76
        state: directory
        mode: "777"
      args:
        chdir: "/apache-tomcat-9.0.76"

    - name: copy/deploy war
      copy:
        src: gameoflife-web/target/gameoflife.war
        dest: /apache-tomcat-9.0.76/webapps/
